// ─── TK GROUP · Rule Book (enforced-rule reference data) ─────────────────────
// The Accounts & Operations rules the ERP actually ENFORCES in code — a guard,
// threshold, rate, lock or throw — recovered from a deep scan of the backend and
// frontend. This is READ-ONLY documentation surfaced in the Rule Book tab; it is
// not evaluated by the Control Tower engine (that is ERP Rules Manager). Each rule
// carries the source file that enforces it. Grouped into 24 domains, tagged
// 'accounts' or 'ops'. Counts are derived, never hand-maintained.

export const RULE_BOOK = [
  { id: 'A', group: 'accounts', title: 'Taxation — GST & Place of Supply', blurb: 'How output/input GST is rated, split across CGST/SGST/IGST, and routed per branch and supply type.', rules: [
    { t: 'Default output/service GST rate is 18%.', r: 'constants/voucherSpecs.js:12' },
    { t: 'Per-module GST rule: Flight/Hotel/Car/Visa/Insurance/Misc = 18% on service charge only; Holiday = 5% package; each carries a tax.kind.', r: 'constants/bookingModules.js:29' },
    { t: 'Intra-state GST posts equal CGST+SGST halves; inter-state posts a single IGST leg.', r: 'posting.builder.js:159' },
    { t: "Supply type is 'foreign' (no Indian GST/TDS) when supplier country is not India/blank.", r: 'util/gstSupplyType.js:75' },
    { t: 'Indian supplier intra vs inter is decided by comparing supplier state code to the branch home state.', r: 'util/gstSupplyType.js:79' },
    { t: 'Branch GST home states: BOM=27 (Maharashtra), AMD=24 (Gujarat), default HO=27.', r: 'util/gstSupplyType.js:43' },
    { t: 'An explicitly-Indian supplier/customer must declare a resolvable state or a guard fires.', r: 'util/gstSupplyType.js:72' },
    { t: 'Every branch owns its own tax ledgers, tagged by branch code (e.g. "CGST Output [BOM]").', r: 'posting.builder.js:44', regime: 'all' },
    { t: 'SVC2 (agency margin) GST is carved GST-inclusive (markup×rate÷(1+rate)) and posted to dedicated per-branch "SVC2 [C/S/I]GST Output" ledgers, separate from regular GST.', r: 'voucherSpecs.js:106 · posting.builder.js:191' },
    { t: 'Regular sale output GST = fares/service-charge GST only; the SVC2 margin GST is separated into so.otherTaxesGst.', r: 'voucherSpecs.js:197' },
    { t: 'Tax regime: NBO/DAR/FBM run VAT (Africa); all other branches run India GST.', r: 'constants/taxRegime.js:11' },
    { t: 'Single VAT rate per Africa branch — Kenya(NBO) 16%, Tanzania(DAR) 18%, DR Congo(FBM) 16%.', r: 'constants/taxRegime.js:13' },
    { t: 'On VAT branches tax routes to a single VAT Input/Output leg vs CGST/SGST/IGST on GST branches.', r: 'posting.builder.js:175' },
    { t: 'NBO and DAR carry a mandated local reporting currency (NBO→KES, DAR→TZS); FBM trades in USD only — no secondary currency.', r: 'constants/taxRegime.js:19' },
    { t: '"Without VAT" (noVat) zeroes booking output tax and applies only on Africa/VAT branches; India always follows the module GST rule.', r: 'voucherSpecs.js:27 · import.service.js:621' },
    { t: 'Africa input VAT is decoupled from the Without-VAT sale flag — it follows the supplier invoice and is still recorded.', r: 'voucherSpecs.js:32' },
    { t: 'Incentive/commission output GST routes through the same CGST/SGST(intra)/IGST(inter) Output heads as a sale so it lands in GSTR-1 with correct place-of-supply.', r: 'posting.builder.js:233' },
  ]},
  { id: 'B', group: 'accounts', title: 'Taxation — Holiday Scheme, TCS & ITC', blurb: 'Tour-operator 5% scheme, date-based TCS under 206C(1G), and input-credit treatment.', rules: [
    { t: 'Holiday package output GST is 5% on the sales consideration (Base Fare + SVC2 margin) only.', r: 'voucherSpecs.js:13,131' },
    { t: "Supplier's 5% GST on a holiday package is always claimed as Input GST (ITC), never re-billed to the customer.", r: 'voucherSpecs.js:135' },
    { t: 'TCS applies only where the module declares it (Holiday) and, when intlOnly, only for an International package.', r: 'voucherSpecs.js:81' },
    { t: 'TCS u/s 206C(1G) rate is 5% for booking dates before 2026-04-01 and 2% on/after — a date-based switch driven by the booking date.', r: 'voucherSpecs.js:90' },
    { t: 'B2B buyers (customer sub-group matching /b2b/) are NOT charged TCS; B2C/B2E are.', r: 'voucherSpecs.js:100,220' },
    { t: 'TCS is added to the total only when: not noVat, not a VAT branch, not B2B, and tcsApplies — computed as so.total×rate.', r: 'voucherSpecs.js:220' },
    { t: 'TCS collected from a customer is credited to "TCS Payable — 206C(1G)" (Duties & Taxes liability), not revenue.', r: 'posting.builder.js:272' },
    { t: 'TCS paid on an overseas package is debited to "TCS Receivable" (Current Asset), recoverable.', r: 'posting.builder.js:293' },
    { t: 'On a purchase return TCS Receivable is reversed (credited); on a refund/cancellation TCS Payable/Receivable reverses to the opposite side.', r: 'posting.builder.js:453,586' },
    { t: 'Bulk import derives the 206C(1G) rate from the booking date (5% pre / 2% post 31-03-2026).', r: 'import.service.js:624' },
  ]},
  { id: 'C', group: 'accounts', title: 'Taxation — TDS, WHT, RCM & Foreign Supplier', blurb: 'Withholding on incentives, regime-aware TDS/WHT, and reverse charge on foreign imports.', rules: [
    { t: 'Supplier-incentive TDS (194H commission) is withheld at 2%, effective 01-Oct-2024.', r: 'constants/incentive.js:26 · voucherSpecs.js:14' },
    { t: 'TDS section defaults: 194C 2%/₹30,000, 194H 2%/₹15,000, 194J 10%/₹30,000, 194D 5%/₹15,000, None 0.', r: 'appConfig.seed.js:8' },
    { t: "A supplier's actual withheld-TDS amount (tdsOverride) wins over the computed rate.", r: 'constants/incentive.js:62' },
    { t: 'TDS withheld from a supplier credits "TDS Payable" (liability); the supplier gets the net.', r: 'posting.builder.js:349,397' },
    { t: 'TDS a customer withholds from a receipt is debited to TDS Receivable (asset), debtor cleared for gross.', r: 'posting.builder.js:365' },
    { t: 'Withholding leg is regime-aware: India→TDS Payable/Duties & Taxes, Africa→WHT Payable/Provisions.', r: 'posting.builder.js:205' },
    { t: 'Withholding-recoverable head is regime-aware: India→TDS Receivable, Africa→WHT Receivable (both Current Assets).', r: 'posting.builder.js:212' },
    { t: 'A foreign supplier cannot withhold Indian 194H TDS — the TDS-receivable leg is dropped and the full incentive reduces the payable.', r: 'posting.builder.js:223' },
    { t: 'creditorNet adds back withheld TDS only for non-foreign suppliers.', r: 'posting.builder.js:240' },
    { t: 'Booking auto-flags foreignSupplier from supplier country (!isIndia) to suppress Indian GST/TDS legs.', r: 'bookingOrders.service.js:395' },
    { t: 'Reverse-charge (RCM) IGST on foreign-supplier service imports is self-assessed at 18% on the full cost, payable and claimable as ITC the same month.', r: 'accounting.service.js:2747' },
    { t: 'RCM applies to purchase / purchase-expense vouchers whose party matches a supplier-master with a non-India country.', r: 'accounting.service.js:2764' },
    { t: "Foreign-supplier normalization clears Indian state/stateCode and sets supplyType='foreign'.", r: 'suppliers.service.js:17' },
    { t: 'An Indian supplier save is blocked (400) unless a state is provided.', r: 'suppliers.service.js:12' },
    { t: 'Output GST on supplier commission/incentive defaults to 0% (treated as trade discount, booked via JV).', r: 'constants/incentive.js:25 · appConfig.seed.js:42' },
  ]},
  { id: 'D', group: 'accounts', title: 'Taxation — Reconciliation, GSTR-2B, Calendar & Alerts', blurb: 'Return-vs-books matching, ITC matching, and statutory due/deposit alerts.', rules: [
    { t: 'Four tax-reco modes enforced: gstr3b-books, vat-books, gstr1-3b, tds-26as with fixed head sets; an unknown mode throws 400.', r: 'taxReco.service.js:21' },
    { t: 'A head is "matched" only when |left−right| ≤ ₹0.01.', r: 'taxReco.service.js:71' },
    { t: 'TDS books value for 26AS reconciliation is taken from withholding.receivable (TDS deducted on our income).', r: 'taxReco.service.js:43' },
    { t: 'Reconciliation period must match YYYY-MM or throws 400.', r: 'taxReco.service.js:30' },
    { t: 'Filing board: GST regime expects GSTR-1/3B/TDS, VAT regime expects a VAT return; status Filed only once a figure is entered.', r: 'taxReco.service.js:113' },
    { t: 'Tax ledgers are bucketed by name into output/input/whtPayable/whtReceivable/tcsPayable/tcsReceivable.', r: 'accounting.service.js:2695' },
    { t: 'Net GST payable = Output − Input (≥0 owed to / <0 refundable from the authority).', r: 'accounting.service.js:2725' },
    { t: 'ITC value of a GSTR-2B line = igst + cgst + sgst + cess; each line keyed uniquely by (branch, period, GSTIN, invoice no).', r: 'gstr2b.service.js:14 · gstr2b.model.js:28' },
    { t: "A GSTR-2B line's match status is constrained to unmatched/matched/mismatch (defaults unmatched).", r: 'gstr2b.service.js:115' },
    { t: 'HSN/SAC code is required and intentionally NOT unique (same SAC spans multiple rate slabs); carries rate + ITC applicability + TCS note.', r: 'hsnCodes.model.js:7,12' },
    { t: 'A statutory due event is Overdue when days-left < 0 and Pending (urgent) when days-left ≤ 7; events keyed by (date, title).', r: 'taxCalendar.service.js:28 · taxCalendar.model.js:18' },
    { t: 'Alert: net GST payable > ₹0.5 raises "GST payable outstanding — deposit & file".', r: 'alerts.service.js:391' },
    { t: 'Alert: undeposited withheld TDS > ₹0.5 raises "deposit by the 7th".', r: 'alerts.service.js:393' },
    { t: 'Alert: undeposited collected TCS > ₹0.5 raises "TCS payable not deposited".', r: 'alerts.service.js:395' },
    { t: 'Sec 40A(3) cash-payment threshold ₹10,000 fires on INR (India) branches only.', r: 'alerts.service.js:179' },
    { t: 'Company tax setup flagged incomplete if GSTIN, PAN, TAN, or GST rates are missing.', r: 'alerts.service.js:421' },
    { t: 'Indian supplier without GSTIN is flagged (cannot pass ITC); without PAN is flagged (higher default TDS); foreigners are informational RCM only.', r: 'suppliers.service.js:113' },
    { t: 'Customer with neither GSTIN nor PAN is flagged as having no B2B tax identity.', r: 'customers.service.js:101' },
  ]},
  { id: 'E', group: 'accounts', title: 'Posting & Journal Integrity', blurb: 'The double-entry invariants every posting must satisfy before it touches the books.', rules: [
    { t: 'The JournalEntry model refuses to save any journal whose total debit ≠ total credit (>₹0.01) in a pre-validate hook.', r: 'journal.model.js:48' },
    { t: 'A journal must have at least two postings (a real double entry).', r: 'journal.model.js:53' },
    { t: "The posting builder throws 422 if built postings don't balance (|Dr−Cr|>0.01) for any category.", r: 'posting.builder.js:945' },
    { t: 'The approval-time validator blocks any voucher whose built postings don\'t balance or produce no postings.', r: 'approvalChecks.js:252' },
    { t: 'The same ledger may not appear on both Dr and Cr of a voucher (self-cancelling wash) — carve-out only for netted refunds.', r: 'approvalChecks.js:262 · posting.builder.js:935' },
    { t: 'A contra/receipt/payment with the same bank on both legs (e.g. ICICI→ICICI) is a same-ledger wash and refused.', r: 'posting.builder.js:935' },
    { t: 'Only approved/saved vouchers hit the books; NON_POSTING statuses (draft/cancelled/pending/rejected/unpushed) clear any journal instead of posting.', r: 'accounting.service.js:77,153' },
    { t: 'Posting clears any prior journal by BOTH voucherId AND vno, making a duplicate/orphan journal structurally impossible.', r: 'accounting.service.js:204' },
    { t: 'On post failure the voucher is reverted (removed on create, back to pending on approve).', r: 'vouchers.service.js:246,311' },
    { t: 'A voucher line carrying an amount but no ledger is refused (would post to a default) — 422.', r: 'accounting.service.js:92' },
    { t: 'A receipt/payment with no party and no non-bank counter-account is refused (would post to a default debtor/creditor) — 422.', r: 'accounting.service.js:100' },
    { t: 'Standalone/imported vouchers must reference existing ledgers — a missing ledger refuses the post (422, stays pending).', r: 'accounting.service.js:83,169' },
    { t: 'Tax ledgers are super-admin-managed and NEVER auto-created — a missing tax head refuses the post (422).', r: 'accounting.service.js:409' },
    { t: 'bankOrCash precedence: explicit bankRef → the ledger chosen on the line → payment mode → generic Cash/Bank fallback (a line-named bank no longer silently posts to Cash).', r: 'posting.builder.js:99' },
    { t: 'Equal CGST/SGST split posts round2(taxAmt/2) each and routes the ±₹0.01 remainder to a Round Off leg so both halves stay equal and the voucher balances.', r: 'posting.builder.js:139' },
    { t: 'All posting amounts are rounded to 2 decimals (round2) at every leg and total.', r: 'posting.builder.js:24,921' },
    { t: 'Purchase creditor / debit-note / purchase-expense party legs are the balancing figure (Σdebits + tax − credits − TDS) so the voucher always balances.', r: 'posting.builder.js:347,464', regime: 'all' },
    { t: 'Opening balances are signed onto the ledger\'s natural side (Cr → negative) when rolling up ledger rows.', r: 'accounting.service.js:480' },
  ]},
  { id: 'F', group: 'accounts', title: 'Numbering & Series', blurb: 'How voucher numbers are minted uniquely and atomically, with self-healing against imports.', rules: [
    { t: 'Every auto-numbered voucher requires a type/category to allocate against — no typeless catch-all counter.', r: 'vouchers.service.js:191' },
    { t: 'Number allocation is atomic via $inc on nextNo (consumes the pre-increment value), seeding the series on first use.', r: 'numberAllocator.js:48' },
    { t: 'allocateUnique skips any already-taken number (self-heals when the counter fell behind imports) instead of throwing, bounded at maxTries.', r: 'numberAllocator.js:87' },
    { t: 'A caller-supplied voucher number must be unique — a duplicate throws 409.', r: 'vouchers.service.js:200' },
    { t: "An explicitly-written vno bumps its (branch, prefix) counter past it via syncSeriesToVno so the next auto number can't collide.", r: 'vouchers.service.js:242 · numberAllocator.js:118' },
    { t: 'The NumberingSeries collection enforces a unique (branch, prefix) index — one counter per pair.', r: 'numbering-series.model.js:12' },
    { t: 'The Voucher vno field is globally unique + required at the schema level.', r: 'vouchers.model.js:30' },
    { t: 'Format substitution replaces {#####} before {####} (superstring guard) with global replace so repeated tokens don\'t leak.', r: 'numberAllocator.js:28' },
    { t: 'peekNext/previewNext is a non-consuming preview and requires branch + type.', r: 'numberAllocator.js:105' },
    { t: 'Numbering-series create requires branch, voucherType, prefix; nextNo (if given) must be a positive integer ≥ 1.', r: 'numbering-series.validator.js:4' },
    { t: 'Manual ledger codes are system-generated as <BRANCH>-MN-<NNNN> for branch ledgers and MN-<NNNN> for org-wide \'ALL\'; suffix zero-padded to 4 digits.', r: 'ledgerCode.js:21,38' },
    { t: 'The client-supplied code is always dropped on create; the server allocates the next free code with up to 25 retries on a duplicate-key race, and never reassigns on update.', r: 'ledgers.service.js:76,99' },
  ]},
  { id: 'G', group: 'accounts', title: 'Ledgers — Wired / Locked Heads', blurb: 'Which ledgers the engine owns and freezes so no user can corrupt reconciliation.', rules: [
    { t: 'Wired ledgers (module trading heads, tax heads, inter-branch mirrors, named control heads) plus any locked ledger are LOCKED for everyone — no create/edit/delete/deactivate via the app (423).', r: 'ledgers.service.js:14' },
    { t: 'A ledger is wired if its name is in WIRED_NAMES, its group starts with "Inter-Branch", it passes isTaxLedger, it is in WIRED_LEAF_GROUPS/WIRED_ROOTS, or its primary root is a wired root.', r: 'wiredLedgers.js:47' },
    { t: 'The entire subtree of Sales Accounts, Purchase Accounts, and Duties & Taxes is treated as engine (wired) territory.', r: 'wiredLedgers.js:18' },
    { t: 'Update is blocked both when the existing ledger is wired/locked AND when an edit would turn a plain ledger INTO a wired head.', r: 'ledgers.service.js:96' },
    { t: 'Branch-presence toggle (hide/unhide/reactivate/clone) refuses to act on any wired/tax/locked head.', r: 'ledgers.service.js:149' },
    { t: 'Engine-minted wired/trading/control ledgers are auto-created LOCKED (never user-editable); party/bank/master auto-creations stay unlocked.', r: 'accounting.service.js:423' },
    { t: 'Ledger source is constrained to system/auto/import/manual and locked defaults false (only super-admin/DB can set locked tax heads).', r: 'ledgers.model.js:40' },
    { t: 'A group name is a wired sub-group (locked, shown ~*) when it exactly matches TRADING_FWD, TRADING_PUR, TAX, or PARTY sets.', r: 'wiredSubGroups.js:40' },
    { t: 'Purchase-side trading sub-groups are always derived as "<forwardName> [Pur]" so they cannot drift from the forward set.', r: 'wiredSubGroups.js:28' },
  ]},
  { id: 'H', group: 'accounts', title: 'Chart & Groups — Frozen Structure', blurb: 'The chart of accounts skeleton is immutable via the API; only seeds/scripts may reshape it.', rules: [
    { t: 'The whole chart structure is frozen: every Parent Group / Group / Sub-Group is non-creatable, non-editable, non-deletable via the API (isMandatory always true).', r: 'groups.service.js:46' },
    { t: 'Creating any group/sub-group via the service always throws 423 (only a super-admin seed/script may add groups).', r: 'groups.service.js:156' },
    { t: 'A rename or re-parent of a custom group is allowed only while it is empty (no child groups and no ledgers).', r: 'groups.service.js:184' },
    { t: 'A custom group cannot be re-parented to a blank/top-level parent — it must keep a parent group.', r: 'groups.service.js:176' },
    { t: 'A group cannot be deleted while it has sub-groups (409) or ledgers filed under it (409).', r: 'groups.service.js:222' },
    { t: 'Every sub-group must nest under an existing parent; there is no way to create a top-level group.', r: 'subgroups.route.js:17' },
    { t: 'The 28 Tally system groups are seeded system:true and are never overwritten by registerGroups/seed.', r: 'tallyGroups.js:143' },
    { t: 'Every ledger must resolve to one of the 28 Tally groups (or a custom sub-group nested under one), fixing its nature and BS/PL statement.', r: 'tallyGroups.js:27' },
    { t: "Legacy/loose group names ('Assets','Income','Cost of Sales'…) are aliased to canonical Tally groups so old free-text ledgers still classify.", r: 'tallyGroups.js:74' },
    { t: 'An unclassified custom sub-group inherits nature/statement by walking UP its parent chain to a classified ancestor (terminating at a system root).', r: 'tallyGroups.js:114' },
    { t: 'topSystemGroup climbs a sub-group up to the primary (id-bearing) Tally group it sits under, keeping the 28 groups atop the Balance Sheet.', r: 'tallyGroups.js:223' },
    { t: 'Indirect Expenses split into Fixed vs Variable heads by explicit expenseType on the node or nearest ancestor.', r: 'tallyGroups.js:165' },
    { t: 'Asset/expense balances sit on Dr, liability/income on Cr (naturalSide); nature derived from group, falling back to subGroup.', r: 'tallyGroups.js:181 · ledgers.model.js:56' },
    { t: 'Liquidity (cash/bank) is classified via the primary Tally group (Cash-in-Hand→cash, Bank Accounts/Bank OD→bank), not a name regex.', r: 'tallyGroups.js:243' },
    { t: 'Cost category names are globally unique; each flags whether it allocates revenue (default on) and non-revenue/capital (default off).', r: 'costCategories.model.js:5' },
  ]},
  { id: 'I', group: 'accounts', title: 'Ledger Scope, Lifecycle, Dedup & ensureLedgers', blurb: 'Branch vs org-wide ownership, duplicate prevention, auto-creation and deactivation.', rules: [
    { t: 'Income/Sales/Purchase/all Expense heads are shared org-wide; taxes/suppliers/customers/loans/banks/capital are branch-owned.', r: 'ledgerScope.js:18' },
    { t: "In single-branch (BOM) operation, scopeForGroup routes a new ledger to the posting branch (or 'BOM'), collapsing the 'ALL' scope.", r: 'ledgerScope.js:40' },
    { t: "A branch-scoped chart query always merges in org-wide ('ALL') ledgers via { $in:[branch,'ALL'] }.", r: 'ledgers.service.js:28 · groups.service.js:126' },
    { t: "getAll stamps each ledger's rootGroup (via topSystemGroup) so a party filed under a sub-group is still typed as Debtor/Creditor in pickers.", r: 'ledgers.service.js:51' },
    { t: "On create, a duplicate ledger name is blocked within the branch AND the org-wide 'ALL' chart (names are the posting join key).", r: 'ledgers.service.js:69' },
    { t: 'assertUniqueName rejects a same-name master (case-insensitive, trimmed) within scope (409), since parties/ledgers join by name.', r: 'util/uniqueName.js:19' },
    { t: 'A ledger cannot be hard-deleted once it has posted transactions (postings reference by name) — deactivate instead (409).', r: 'ledgers.service.js:111' },
    { t: 'ensureLedgers reuses an existing master when a casing/spacing/punctuation variant of the name already exists rather than minting an AUTO- duplicate; dedupes within a run by name|branch.', r: 'accounting.service.js:399,407' },
    { t: "The posting engine auto-creates missing ledgers as <branch>-AUTO-<name>, source 'auto', defaulting group to Suspense Account.", r: 'accounting.service.js:413' },
    { t: "Duplicate-key (11000) races during auto-creation are swallowed so concurrent posts don't fail.", r: 'accounting.service.js:427' },
    { t: 'Ledger lists default to active-only AND drop presence-hidden ledgers; the Masters screen reveals both only via its "Show hidden & inactive" toggle (includeInactive=true) and an explicit active= filter wins.', r: 'ledgers.service.js:35' },
    { t: 'The branch-presence toggle HIDES a ledger (hidden:true) rather than deactivating it, leaving accounting history untouched; enabling unhides, else reactivates, else clones from a donor branch (BOM preferred) with opening 0.', r: 'ledgers.service.js:146,154' },
    { t: "The org-wide 'ALL' pool has no presence toggle (422 — a specific branch must be chosen).", r: 'ledgers.service.js:138' },
    { t: 'Only structural skeleton ledgers (SKELETON_GROUPS) are replicated to other branches; named parties/banks/capital are skipped.', r: 'chartReplicator.js:60' },
    { t: 'India tax heads copy only to GST branches; VAT (Africa) branches get a generated VAT/WHT skeleton and stale India heads are removed.', r: 'chartReplicator.js:83' },
    { t: "Replication is idempotent/additive (upsert by code, never drops), re-codes as <branch>-<sourceCode>, re-currencies, and cannot target 'ALL' or the source branch itself (422).", r: 'chartReplicator.js:174,198' },
  ]},
  { id: 'J', group: 'accounts', title: 'Cost Centres', blurb: "The branch-prefixed leaf model that drives module P&L and the Int'l/Domestic split.", rules: [
    { t: 'The 9 leaf cost centres (FLT-INT/DOM, HOL-INT/DOM, HOT, VIS, CAR, INS, MISC) plus 9 Inter-Branch leaves are immutable, code-seeded, and served read-only (no CRUD API).', r: 'costCenters.js:5' },
    { t: 'Each cost-centre code is stamped branch-wise (BOM-FLT-INT) whose logical baseCode (FLT-INT) drives all module/label/resolution rules.', r: 'costCenters.js:104' },
    { t: 'Standard codes strip the branch prefix to their base so they merge across branches in consolidated P&L; custom codes keep their full code as their own group key.', r: 'costCenters.js:119' },
    { t: 'Cost-centre uniqueness is enforced per (branch, code) via a compound unique index.', r: 'costCenters.model.js:24' },
    { t: 'The 9 standard cost centres may be renamed/reordered/deactivated but code/branch is immutable and they can never be hard-deleted (deactivate instead, 403).', r: 'costCenters.service.js:58,73' },
    { t: 'A custom cost-centre create rejects a duplicate (branch, code) (409) and a blank code (400).', r: 'costCenters.service.js:38' },
    { t: 'Standard cost centres are seeded per branch insert-if-absent (never overwrite) so Super-Admin renames/deactivations survive reboot.', r: 'costCenters.seed.js:16' },
    { t: 'A voucher\'s leaf resolves by precedence: explicit tag → single-leaf module → Int\'l/Domestic split → module "Unspecified" bucket.', r: 'costCenters.js:156' },
    { t: 'A multi-leaf module (Flights/Holiday) with no packageType resolves to \'\' (NOT a silent Domestic default) so the approval gate refuses it until tagged.', r: 'bookingModules.js:116' },
    { t: 'A non-standard explicit tag is honoured as its own custom (Super-Admin) leaf, keyed by its full branch-wise code.', r: 'costCenters.js:169' },
    { t: "Only sale/purchase/refund/reissue legs carry a cost centre; receipt/payment/contra/journal legs → ''.", r: 'accounting.service.js:37,48' },
  ]},
  { id: 'K', group: 'accounts', title: 'Bookings — Leg Model & Modules', blurb: 'The SO/PO/GP folder: which products may carry extra purchase legs, and of what type.', rules: [
    { t: 'Only SF (Flight) may add a Misc leg, SH (Holiday) may add any component (SF/SHT/SC/SV/SI/SM), SV (Visa) may add Visa/Misc/Insurance; all other modules are single-leg (1 SO : 1 PO).', r: 'bookingModules.js:96' },
    { t: 'There is no per-parent leg COUNT cap — only the leg\'s module TYPE is constrained.', r: 'bookingModules.js:95' },
    { t: 'A booking whose module is not in ALLOWED_LEG_MODULES must carry zero extra purchase legs, else approval is refused.', r: 'approvalChecks.js:169' },
    { t: "Each additional leg's module must be a valid BOOKING_MODULE and appear in the parent's allow-list, else blocked — re-enforced server-side so a raw API call can't bypass the form.", r: 'approvalChecks.js:162,172' },
    { t: 'The purchase-leg schema constrains a leg\'s module to SF/SH/SHT/SC/SV/SI/SM (no reversal modules as legs).', r: 'bookingOrders.model.js:29' },
    { t: 'Each N-PO leg carries its own module→purchaseType, supplier, cost centre and Tally ref, and spawns its own Purchase voucher on approval.', r: 'bookingOrders.service.js:924' },
    { t: 'The 7 forward modules map to a purchase voucher type, seeded cost centre and sale-side tax rule (SF·Flight … SM·Misc).', r: 'bookingModules.js:25' },
    { t: 'RF (Refund) and RI (Reissue) are reversal modules requiring a link to the original sale; kept out of SALE_TYPES so no Sales/Purchase component ledgers are built for them.', r: 'bookingModules.js:73' },
    { t: 'A booking master\'s module is constrained to SF/SH/SHT/SC/SV/SI/SM/RF/RI (schema enum); an unknown module is rejected at create/approve/validation.', r: 'bookingOrders.model.js:49 · approvalChecks.js:99' },
    { t: 'A no-supplier (Misc) booking has GP = the entire sale net (100% margin) and spawns only the Sales voucher.', r: 'bookingOrders.model.js:57' },
  ]},
  { id: 'L', group: 'accounts', title: 'Sales Income Split (SVF / SVC2) & Gross Profit', blurb: 'Base service fee vs markup, and how GP is computed and legitimately can be ≤ 0.', rules: [
    { t: "The internal 'markup' head posts to the 'SVC2' ledger (billed \"Service Charge - 2\") and 'ssvc' posts to the 'SVF' ledger (Service Fee).", r: 'bookingModules.js:221' },
    { t: 'For non-package modules the SVC2 sale head stores the margin NET of its carved GST (markup − gstMk); SVF stores the full ssvc.', r: 'voucherSpecs.js:211' },
    { t: 'Sale side seeds component ledgers fares + SVC2 + SVF (non-package) or fares + Supp SVCHG + SVC2 (holiday package); purchase side seeds fares + Supp SVCHG.', r: 'bookingModules.js:248' },
    { t: 'Approval verifies both split GSTs: so.gst must equal auto-computed regular output GST and so.otherTaxesGst must equal 18% on the SVC2 margin.', r: 'approvalChecks.js:216' },
    { t: 'GP = saleNet − purchaseNet, where saleNet = so.total − gst − otherTaxesGst − tcs and purchaseNet = po.total − gst − tcs − incentive.', r: 'bookingOrders.service.js:266' },
    { t: 'Supplier incentive/commission ADDS to GP (reduces cost); the 2% 194H TDS is a balance-sheet withholding asset and never affects GP.', r: 'bookingOrders.service.js:268 · voucherSpecs.js:240', regime: 'all' },
    { t: 'Across the N-PO model GP = saleNet − Σ(purchaseNet of primary + every leg).', r: 'bookingOrders.service.js:281' },
    { t: "For the Holiday package model GP = SVC2 margin − Supplier Service Charge; the supplier's 5% GST is claimed as ITC and never re-billed.", r: 'voucherSpecs.js:123' },
    { t: 'GP% = (GP ÷ so.total)×100, defaulting to 0 when so.total is not > 0 (no divide error).', r: 'bookingOrders.service.js:285' },
    { t: 'GP is NOT gated on sign — no validation blocks GP = 0 or negative; a zero/negative-margin booking still approves.', r: 'approvalChecks.js:96' },
    { t: 'Trading membership (feeding module GP) is tested by each group\'s PRIMARY system head, so custom module sub-groups sit ABOVE Gross Profit, not below.', r: 'accounting.service.js:611 · accounting.repository.js:60' },
    { t: 'Gross Profit is TRADING-only: {Sales, Direct Income, Closing Stock} minus {Purchases, Direct Expenses, Opening Stock}, keyed on primary head.', r: 'accounting.service.js:608,689' },
    { t: 'A booking referencing an un-seeded trading head stays PENDING and is refused (no trading head auto-created).', r: 'accounting.service.js:187' },
    { t: 'GP≤0 leak alert fires on bookings, EXEMPTING RF/RI reversals, visa/insurance pass-throughs and inter-branch deals.', r: 'alerts.service.js:596,599' },
  ]},
  { id: 'M', group: 'accounts', title: 'Refunds — Full Reversal, Carry-Through & Cost Centre', blurb: 'A refund unwinds the original sale+purchase; service fee is retained, party and cost-centre preserved.', rules: [
    { t: 'A refund with a resolved original sale posts via FULL reversal; partialAmount>0 goes to the partial path; no original → net-lines fallback.', r: 'posting.builder.js:745' },
    { t: 'refundFullReversal reverses ONLY the airline cost (base+taxes+markup) of both the original sale and its linked purchase.', r: 'posting.builder.js:643' },
    { t: 'reverseAirlineCost retains the service charge and its GST but reverses the margin, base taxes and margin GST of the reversed leg.', r: 'posting.builder.js:556', regime: 'all' },
    { t: 'Any leg matching \\bsvf\\b (service fee) is RETAINED and never reversed on a refund.', r: 'posting.builder.js:515' },
    { t: 'A booking-path reversal is always a FULL unwind — partialAmount is pinned to 0 so a stale value can\'t divert to the partial path.', r: 'bookingOrders.service.js:498' },
    { t: 'Refund postings net every ledger (incl. the customer) to a single signed line; net-zero ledgers drop (avoids same-ledger wash).', r: 'posting.builder.js:604,718' },
    { t: "The reversal's balancing party leg is forced onto the REFUND voucher's own customer/supplier, falling back to the original booking's party only when the refund leaves them blank.", r: 'posting.builder.js:643' },
    { t: "Approving a reversal resolves the ORIGINAL sale's SVC2 head so the retained margin posts under Sales (not Indirect Income).", r: 'bookingOrders.service.js:853' },
    { t: 'Refund-only economics (supplier cancel + GST, incentive clawback + GST + TDS) are carried onto the spawned voucher so the approved JV matches the live preview.', r: 'bookingOrders.service.js:455', regime: 'all' },
    { t: 'The airline cancellation penalty is booked as our cost and, when cancelRecover (default true), recovered from the customer as income.', r: 'posting.builder.js:687' },
    { t: 'Commission/incentive income (+ output GST) is clawed back and the supplier-withheld TDS restored on cancellation; foreignSupplier drops the 194H TDS leg.', r: 'posting.builder.js:709', regime: 'all' },
    { t: 'Refund-only fields (supplierCancel, incentive*) are zeroed when the module is not RF (a reissue never posts cancellation/clawback).', r: 'bookingOrders.service.js:461' },
    { t: "A refund/reissue journal INHERITS the original booking's cost-centre and re-stamps it onto the refund voucher, so reversed legs sit with the original in the Int'l/Domestic drill.", r: 'accounting.service.js:52,217' },
    { t: 'Credit Note is retired — NOT among the allowed voucher parent types; Debit Note (purchase return) is enabled with a dedicated posting builder.', r: 'voucherTypes.model.js:4 · posting.builder.js:429,901' },
    { t: 'A refund functions as the credit-note: naming a bill via againstInvoice settles that bill in the drill.', r: 'vouchers.service.js:1048' },
  ]},
  { id: 'N', group: 'accounts', title: 'Bank, Client, Supplier & Tally Reconciliation', blurb: 'Matching tolerances, sign conventions, and import de-duplication across all four statement engines.', rules: [
    { t: 'A ledger reconciles as a bank only if its resolved group is Bank Accounts or Bank OD Accounts.', r: 'bankReco.service.js:25' },
    { t: "Bank statement queries scope to {branch,'ALL'} so a bank-ledger name shared across branches never mixes/wipes another branch's lines.", r: 'bankReco.service.js:43' },
    { t: 'Auto-match requires amount+direction agreement (tol 0.01) and rejects pairs >5 days apart with no reference link.', r: 'bankReco.service.js:308,327' },
    { t: 'A BRS is "balanced" only when derived-vs-actual bank balance differ by ≤0.01.', r: 'bankReco.service.js:266' },
    { t: 'setStatus rejects any status outside the RECON_STATUS enum (400); reverting a line to unreconciled clears its match key/vno/type.', r: 'bankReco.service.js:396,403' },
    { t: 'Recon-status: one row per (branch, account, period) unique index; accountType ∈ bank|client|supplier|other|accruals; status ∈ pending|reconciled.', r: 'reconStatus.model.js:13,22' },
    { t: 'Marking reconciled stamps by/at; reverting to pending clears them; branch summary always rolls over the fixed six-branch list [BOM,AMD,BOMMB,NBO,DAR,FBM].', r: 'reconStatus.service.js:9,58' },
    { t: 'A ledger is a client if its top system group is Sundry Debtors (via topSystemGroup, catching custom sub-groups).', r: 'clientReco.service.js:35' },
    { t: 'Client is an ASSET — signs do NOT flip: statement DEBIT reconciles against book DEBIT (both signed = debit−credit).', r: 'clientReco.service.js:381' },
    { t: 'Client allocation() FIFO-matches receipts↔invoices purely to SURFACE open items and writes NOTHING to the books.', r: 'clientReco.service.js:229' },
    { t: 'Manual match sets reconciled when |variance|≤0.01 else partial (variance recorded).', r: 'clientReco.service.js:467' },
    { t: 'Supplier is a LIABILITY (Sundry Creditor) so signs flip: statement DEBIT reconciles against book CREDIT.', r: 'supplierReco.service.js:249' },
    { t: "Tally↔ERP matches same-direction (Tally debit ↔ book debit on the ledger's own convention); >5-day gaps with no ref link are rejected.", r: 'tallyReco.service.js:150,151' },
    { t: 'All four statement engines share import guards: skip blank rows and exact-duplicate rows (date|debit|credit|normalized-ref) so re-importing never double-counts.', r: 'clientReco.service.js:344' },
  ]},
  { id: 'O', group: 'accounts', title: 'Settlement, On-Account & Ageing', blurb: 'Bill knock-off is explicit and manual; nameless and cross-type parties are excluded.', rules: [
    { t: 'There is NO FIFO auto-apply in settlement: a bill is knocked off only by an explicit allocation naming its vno (or a refund/CN via againstInvoice); everything else is a standing advance settled bill-wise later.', r: 'vouchers.service.js:906,1021' },
    { t: 'Bill-wise allocations cannot exceed the voucher total (422); only receipts/refunds/payments/debit-notes are settleable.', r: 'vouchers.service.js:1372' },
    { t: 'getOpenBills with no party returns empty (never settles a nameless party).', r: 'vouchers.service.js:918' },
    { t: 'Only posted vouchers count as settleable bills/receivables (excludes draft/cancelled/pending/rejected/deleted/unpushed).', r: 'vouchers.service.js:1131' },
    { t: 'A JV/contra party leg on the party\'s NATURAL side becomes an invoice-shaped open item; the opposite leg is NOT a settlement (ledger-visible only).', r: 'jvOpenItems.js:9,68' },
    { t: "JV open-item side map is keyed by branch::name so a same-named ledger that is a Debtor in one branch and Creditor in another can't collide/mis-side.", r: 'jvOpenItems.js:26' },
    { t: 'On-account = unapplied remainder to a TRADE party; a settlement with NO party is a non-trade payment and excluded (no nameless "—" on-account row).', r: 'accounting.service.js:2462' },
    { t: 'On-account excludes customer-refund vouchers (partyType customer) so an over-refund excess isn\'t double-counted as a supplier advance.', r: 'vouchers.service.js:1334' },
    { t: 'Ageing counts only posted vouchers (excludes NON_POSTING + deleted) and the as-on snapshot drops every voucher dated after asOf.', r: 'accounting.service.js:2354,2363' },
    { t: 'Ageing emits no row for parties with nothing open and nothing on-account (|total|≤0.01 and |onAccount|≤0.01).', r: 'accounting.service.js:2478' },
    { t: 'Supplier (purchase) bills age NET of withheld TDS so payables tie to the Sundry Creditors control; sale bills stay gross.', r: 'accounting.service.js:2450', regime: 'all' },
    { t: 'Collections board lists only parties overdue >0.5 in 30/60/90 buckets, sorted worst-first.', r: 'collections.service.js:37' },
  ]},
  { id: 'P', group: 'ops', title: 'Voucher Lifecycle — Entry Gate, Locking & Edit', blurb: 'Nothing posts on entry; posted vouchers are read-only; every edit re-queues for approval.', rules: [
    { t: "NO voucher of any category posts on entry — every creation path is forced to PENDING except an internal booking-leg spawn (source:'booking').", r: 'vouchers.service.js:218' },
    { t: "A spoofed source:'booking' from a non-internal caller is downgraded to manual/pending so it can't bypass the pending gate.", r: 'vouchers.service.js:220' },
    { t: 'No voucher may carry a future posting date — only today or a past date (IST-anchored), on create, edit and manual API path.', r: 'vouchers.service.js:19,162 · vouchers.validator.js:24' },
    { t: 'A deleted voucher is view-only and can never be edited, re-posted, or re-approved (409).', r: 'vouchers.service.js:255' },
    { t: 'An approved/posted (saved) voucher is read-only and cannot be edited directly — must be revoked to Pending first (409).', r: 'vouchers.service.js:809' },
    { t: 'A master-driven (locked) voucher (booking/inb/expense-order/adm/acm) can only be edited/removed via its master (409).', r: 'vouchers.service.js:778' },
    { t: 'Every voucher edit must carry a reason (400), and any edit forces the voucher back to PENDING (clearing prior sign-off).', r: 'vouchers.service.js:816,831' },
    { t: 'The editReason is never persisted onto the voucher document.', r: 'vouchers.service.js:819' },
    { t: "Per-voucher in-process approval lock serializes concurrent approve/push/revoke/rollback of the same id so a double-submit can't double-post; approve is idempotent.", r: 'vouchers.service.js:38,270' },
    { t: 'Branch-scope guard: a scoped user gets 404 on any id operation outside their branch list (cross-branch IDOR guard).', r: 'vouchers.service.js:107 · vouchers.controller.js:8' },
    { t: "In group-atomic approveMany, if any leg fails the sibling legs this call posted are rolled back — a deal can't sit half-approved.", r: 'vouchers.service.js:601' },
    { t: 'Voucher type/category must be one of the fixed VALID_TYPES/VALID_CATS sets (validator + model enum).', r: 'vouchers.validator.js:6,7 · vouchers.model.js:39' },
    { t: 'Voucher schema mandatory fields: vno, type, category, branch, date, total; date must be strict ISO YYYY-MM-DD.', r: 'vouchers.model.js:30 · vouchers.validator.js:22' },
    { t: 'Payment Run requires a supplier and positive amount on every line and rolls back all created vouchers if any fails (all-or-nothing).', r: 'vouchers.service.js:1484,1506' },
    { t: '"Entered by" is taken from the JWT, never trusted from the request body.', r: 'vouchers.controller.js:50' },
    { t: 'Exactly one fiscal year may be current — saving one as isCurrent clears the flag on every other year; fiscal-year v is required and unique.', r: 'fiscalYears.model.js:6,16' },
  ]},
  { id: 'Q', group: 'ops', title: 'Approval Chain (3-Level) & Escalation', blurb: 'Check → Verify → Approve, with FM the last posting gate and amount-tier Director/Owner escalation.', rules: [
    { t: 'Every books-posting entry walks a three-level chain: Check (L1, branch accountant) → Verify (L2) → Approve (L3); only final Approve posts the journal.', r: 'approvalChain.js:103' },
    { t: 'Final Approve is blocked while the entry is still awaiting Check, Verify, Director or Owner stage.', r: 'approvalChain.js:157' },
    { t: 'Verify requires Check first, and only a configured verifier (default sughra@travkings.com) or Super Admin may Verify.', r: 'approvalChain.js:130' },
    { t: 'Final Approve requires a configured approver (default faiz@travkings.com) — FM is LAST before posting.', r: 'approvalChain.js:166' },
    { t: 'The chain applies only to CRM-origin entries or branch entries flagged reviewChain:true; ERP/legacy data keeps single-step Approve.', r: 'approvalChain.js:65' },
    { t: 'Super Admin can act at any level (emergency override); internal/system callers (no actor) bypass the chain gate.', r: 'approvalChain.js:158' },
    { t: 'A verifier (AE) verifies and stops there — final approval is the configured approver\'s. The approval.ae_can_approve flag that used to elevate her was RETIRED (2026-07): it collapsed maker-checker by letting the same hand verify and approve one voucher. The only way now is the explicit one — naming her in approval.approveEmails, which the panel reports as an SoD overlap.', r: 'approvalChain.js · canFinalApprove' },
    { t: 'Editing/revoking/rejecting an entry RESETS the whole chain (all check/verify/director/owner stamps cleared) — must re-enter at L1.', r: 'approvalChain.js:171' },
    { t: 'A voucher over voucherEscalate needs a Director sign-off and over voucherDual needs an Owner sign-off BEFORE FM\'s final Approve — dormant unless approval.escalation_signoffs is engaged.', r: 'approvalChain.js:89' },
    { t: 'Director sign-off requires Verify done and only the configured Director (default farhan@travkings.com) may sign.', r: 'approvalChain.js:137' },
    { t: 'Owner sign-off requires Verify done and only the configured Owner (default afshin.dhanani@kingsgroupco.com) may sign.', r: 'approvalChain.js:143' },
    { t: 'Check/Verify actions are only allowed on a Pending entry.', r: 'approvalChain.js:124' },
    { t: 'A branch-accountant ERP entry is routed into the chain (pre-stamped checkedBy so it starts at Verify) when the Branch Accountant is switched under control (control.role.branch_accountant).', r: 'vouchers.service.js' },
    // ── control.role.branch_accountant · "CRM is the system of record" (all dormant while OFF)
    { t: 'Under Branch Accountant control the accountant can no longer RAISE the four CRM-sourced documents — an SO/PO/GP booking, an inter-branch deal, a refund or a reissue are refused at save (403). They arrive from the CRM instead.', r: 'entryRights.js · assertMayOriginate' },
    { t: 'The origination block covers POST /booking-orders (every SO/PO/GP module plus RF/RI) and POST /inter-branch (the seller raising a deal). It does NOT cover /inter-branch/convert — a buyer accepting a deal another branch pushed is acceptance, not origination, and it still walks the buyer\'s own chain.', r: 'entryRights.js · SCOPE' },
    { t: 'The block never catches the CRM service token (it authenticates as super_admin), the bulk importer or the INB buyer-seed (both call the service directly with no actor) — only a real Branch Accountant at the HTTP route.', r: 'entryRights.js · branchAccountantUnderControl' },
    { t: 'Payments, receipts, journals and contras are NEVER blocked — the CRM neither knows nor emits them. Only the four commercial documents come from the CRM.', r: 'entryRights.js · SCOPE' },
    { t: 'Under Branch Accountant control, Check (level 1) becomes the Branch Accountant\'s step alone — the verifier can no longer give it. The Owner and a Super Admin keep an override so one absent accountant cannot strand a document. While OFF, any user with branch access may Check (unchanged).', r: 'approvalChain.js · canCheck' },
    { t: 'Under Branch Accountant control, giving the Check LOCKS the entry to the accountant (423) — it is now with the verifier and they can no longer edit it. The way back is a rejection: reject clears checkedBy, returning it to them for correction. The verifier, Owner and Super Admin are unaffected, and their edit resets the chain to L1.', r: 'approvalChain.js · assertMayEditUnderChain' },
    { t: 'CAUTION on engaging Branch Accountant control: the CRM booking bridge emits SALE bookings only — it has no refund or reissue path — so while the rule is ON a refund has no route into the branch at all. Preview impact reports this against real history before the Owner engages it.', r: 'flags.impact.js · control.role.branch_accountant' },
    { t: 'Default configurable voucher chain is Verify (AccountsExecutive) → Approve (FinanceManager); role ranks BranchAccountant 1 < AE 2 < FM 3 < Director 4 < Owner 5.', r: 'approvalEngine.js:10,12' },
    { t: 'Chain levels at or below the maker\'s own rank are dropped (a senior maker needs fewer approvals).', r: 'approvalEngine.js:84' },
  ]},
  { id: 'R', group: 'ops', title: 'Segregation of Duties & Policy Guard', blurb: 'Maker≠approver, amount tiers, cash ceilings, back-date and mandatory-document limits (fail-closed).', rules: [
    { t: 'An approver can never be the maker of the same document (segregation-of-duties block).', r: 'policyGuard.js:81' },
    { t: 'A voucher over the "dual" ceiling can only be approved by the Owner; over "escalate" a branch-level approver is not senior enough.', r: 'policyGuard.js:88' },
    { t: 'approve() passes maker identity, maker/approver roles and amount into the guard checkpoint to enforce SoD and amount tiers.', r: 'vouchers.service.js:274' },
    { t: 'Out-of-scope branch actions are blocked.', r: 'policyGuard.js:43' },
    { t: 'Posting/editing into a locked period is blocked.', r: 'policyGuard.js:46' },
    { t: 'A cash payment over cashMaxPayment (default ₹20,000) is blocked.', r: 'policyGuard.js:50 · limits.js:19' },
    { t: 'An entry back-dated beyond backdateDays (default 3) is blocked.', r: 'policyGuard.js:56 · limits.js:21' },
    { t: 'A cash receipt pushing on-hand cash over cashMaxOnHand (default ₹100,000) is blocked.', r: 'policyGuard.js:65 · limits.js:20' },
    { t: 'A doc-required category (payment/purchase/expense/ADM/ACM) created with no attachment is blocked when entry.mandatory_docs is ON.', r: 'policyGuard.js:75 · guard.js:66' },
    { t: 'The guard is fail-closed: any unexpected error blocks, never silently allows. (The lighter TK Group integration guard fails OPEN so it never blocks the live path.)', r: 'policyGuard.js:108 · tk-group/integration.js:34' },
    { t: 'Permission model = 7 actions (view/create/edit/delete/approve/print/export) plus high-risk toggles approve_high(>₹50,000), see_cost, see_gp_pct, see_salaries, edit_locked, delete_any.', r: 'permissions.js:10,12' },
    { t: 'Approval-limits seed defines amount tiers per role × voucher type (AE ≤₹50k, Sr.AE ≤₹200k, SFM ≤₹2.5M, Director above) driving escalation.', r: 'approvalLimits.seed.js:4' },
    { t: 'Field-access defaults gate sensitive fields (Salary, Credit Limit, Bank Account, Vendor PAN) per role as View+Edit/View/Hidden.', r: 'fieldAccess.seed.js:3', regime: 'all' },
  ]},
  { id: 'S', group: 'ops', title: 'Master / Config Governance — Owner Sole Approver', blurb: 'Structural and config changes queue as change-requests; only the Owner can finally approve them.', rules: [
    { t: 'Every master/config write is guarded; when engaged, a non-Owner write is staged as a ChangeRequest and NOTHING is written until the Owner approves.', r: 'masterGuard.js:65' },
    { t: 'The Owner\'s own master writes apply directly (final authority, no self-queue).', r: 'masterGuard.js:64' },
    { t: 'Config/governance changes (config/flag/period_lock/master/credit_policy/target_budget/hr) route through a LOCKED Owner-only meta-rule — Owner is sole approver, not configurable.', r: 'approvalEngine.js:21,80' },
    { t: 'Decision-stream docs (credit_limit/funds_release/counterparty/investment) go Director-first, escalating to Owner over threshold; counterparty & investment are ALWAYS dual.', r: 'approvalEngine.js:57' },
    { t: 'Only a role that is an unsigned level of a change-request\'s chain may approve/reject it; it applies only when EVERY role in its chain has signed.', r: 'changeRequest.service.js:19,192' },
    { t: 'Rejecting a change-request requires a mandatory reason.', r: 'changeRequest.service.js:196' },
    { t: 'Change-request routes are gated to central-control roles (Owner/Director/Finance Manager/Sr. Accounts Executive).', r: 'changeRequest.route.js:19' },
    { t: 'ERP-access grants/revokes route through the master gate — a non-Owner grant is queued (202) for the Owner.', r: 'userAccess.controller.js:113' },
    { t: 'Any CRUD master write strips system fields (_id/__v/timestamps) to block mass-assignment.', r: 'crudFactory.js:21' },
    { t: 'Rules Manager (monitoring rules) and User Rules Manager are Owner-only (Super Admin).', r: 'monitoringRules.route.js:8 · userRules.route.js:9' },
    { t: 'System monitoring-rules and user-rules are read-only (no edit/status-change/delete); new rules land \'draft\' (inactive) until activated, with only legal status transitions allowed.', r: 'monitoringRules.service.js:95 · userRules.service.js:90' },
    { t: 'Seeded system invariants document enforced-in-code rules: voucher must balance, no future-dated entry, approved voucher locked, wired ledgers locked, refund originals must resolve.', r: 'monitoringRules.seed.js:8' },
    { t: 'A user-access rule requires a positive ceiling (approval-limit), from+to (time-window), or ≥1 value (branch/module/permission).', r: 'userRules.service.js:38' },
  ]},
  { id: 'T', group: 'ops', title: 'Revoke & File-Revoke Cascade', blurb: 'Explicit, approver-only revoke that unwinds whole files and blocks on locked / reconciled / live-refund.', rules: [
    { t: 'Revoking a posted voucher/booking is approver-only (Super Admin/Director/Sr Finance Mgr/Sr Accounts Exec).', r: 'vouchers.controller.js:25 · bookingOrders.controller.js:88' },
    { t: 'Only an approved/saved/unpushed voucher (or an approved booking) may be revoked, and a non-empty reason is mandatory.', r: 'vouchers.service.js:368,371' },
    { t: 'Revoke BLOCKS a bank-reconciled receipt/payment (unreconcile first).', r: 'vouchers.service.js:502' },
    { t: 'Revoke BLOCKS a master-driven (locked) voucher — must be revoked via its master.', r: 'vouchers.service.js:492' },
    { t: 'Revoke BLOCKS a pushed INB leg (handed to buyer branch).', r: 'vouchers.service.js:499' },
    { t: 'Revoke BLOCKS when a live (approved/saved) refund/reissue reverses one of the entry\'s invoices.', r: 'vouchers.service.js:507 · bookingOrders.service.js:1280' },
    { t: 'The unwind must be COMPLETE then VERIFIED (journal absence + no reconciled/partial bank line still matching the vno) before status flips — never a half-revoke (throws 500 and leaves it approved).', r: 'vouchers.service.js:404' },
    { t: 'Revoke keeps every voucher number (unlike cancel/reject/delete) so re-approval reproduces identical vouchers under identical numbers.', r: 'bookingOrders.service.js:1244' },
    { t: 'A file revoke un-posts ALL spawned legs (sale + primary purchase + every N-PO leg) via a single chokepoint — never one leg alone.', r: 'bookingOrders.service.js:1253' },
    { t: 'Hybrid settlement release: a settler touching ONLY this file\'s bills is FULL-revoked to Pending; a settler that also settled unrelated bills is only UN-allocated for this file\'s share.', r: 'vouchers.service.js:415' },
    { t: 'The cascade stays one level deep — shared settlers are never themselves revoked, only unallocated.', r: 'vouchers.service.js:420' },
    { t: 'A self-contained settler that is bank-reconciled hard-BLOCKS the file revoke.', r: 'vouchers.service.js:440' },
    { t: 'Cancel/reject of an approved booking un-post the spawned sale + all purchase legs and CLEAR their vnos.', r: 'bookingOrders.service.js:1194' },
    { t: 'Deleting a voucher requires Super Admin or Director, a reason, and burns the voucher number (never reused).', r: 'vouchers.controller.js:14' },
  ]},
  { id: 'U', group: 'ops', title: 'Inter-Branch — Conventions, INB Push & Reconciliation', blurb: 'Sister branches trade as normal creditors/debtors; INB has its own two-step push and agreement check.', rules: [
    { t: 'Inter-branch (Travkings) customer deals must be entered via the INB Voucher, never SO/PO/GP (blocked at create/edit/validation), except an INB reversal.', r: 'approvalChecks.js:106 · bookingOrders.service.js:810' },
    { t: 'The buyer side of a pushed INB deal (inter-branch SUPPLIER) IS a legitimate normal-creditor SO/PO/GP purchase and is not blocked (direction-specific guard keys on the customer side only).', r: 'approvalChecks.js:82' },
    { t: "An INB link is born 'unpushed' — hidden from the buyer branch until Approved & Pushed.", r: 'inb.service.js:287' },
    { t: 'Push requires BOTH legs already Approved; only an approved INB voucher can be pushed; push is idempotent.', r: 'inb.service.js:306 · vouchers.service.js:333' },
    { t: 'Push does not post to books; it locks the approved legs (pushed:true), opens the link to the buyer, and auto-seeds a pending buyer-branch booking.', r: 'inb.service.js:301,319' },
    { t: 'A pushed leg/deal is LOCKED and can no longer be revoked (handed to the buyer branch).', r: 'inb.service.js:624' },
    { t: 'An INB deal can only be edited while BOTH legs are fully Pending (revoke first otherwise); revoke requires a reason and blocks if a bank-reconciled settler hangs off it.', r: 'inb.service.js:450,620,630' },
    { t: 'Inter-branch current accounts are named "TK- <other> Branch", coded <branch>-IB-<other>, filed under Current Assets › Branches, one per OTHER branch (never itself).', r: 'chartReplicator.js:137' },
    { t: 'A branch\'s own "TK- <branch> Branch" ledger cannot be created inside that same branch (422).', r: 'ledgers.service.js:171' },
    { t: 'Inter-branch purchase legs post to dedicated <pfx>-<component> [IB-Pur] ledgers under "Inter-Branch <leaf> [Pur]", not shared forward [Pur] heads; the INB discount posts to "Inter-Branch Discount [IB]".', r: 'inb.service.js:100,139' },
    { t: 'Inter-branch is an AGREEMENT check with NO elimination: selling branch = Debtor (Dr), buying branch = Creditor (Cr) under the "INTER BRANCH" sub-group.', r: 'interbranch.service.js:1' },
    { t: "A pair is reconciled only when signed(A→B)+signed(B→A) ≈ 0 (|difference| ≤ 0.01); each ledger's balance is read from its OWNER branch's trial balance — never cross-branch.", r: 'interbranch.service.js:57,74' },
    { t: 'Inter-branch FX is manual/not auto-consolidated: balances compared as-booked per branch; consolidated ageing refuses to merge across currencies.', r: 'accounting.service.js:2505' },
    { t: 'An INB refund/reissue is NOT an SO/PO/GP booking — it becomes a single PENDING RF/RI voucher routed to the INB approvals window; isInbRefund classifies it by the INB/ prefix on againstInvoice/linkNo.', r: 'bookingOrders.service.js:533 · vouchers.service.js:154' },
    { t: "An INB refund's actual reversal is driven off againstInvoice/againstPurchase via originalsFor, reversing the real INB sale+purchase; the INB SVF margin (\\bsvf\\b) is retained.", r: 'inb.service.js:666,681' },
  ]},
  { id: 'V', group: 'ops', title: 'Branch Isolation & Tenancy', blurb: 'Data never crosses branches; only full-scope roles see the consolidated view.', rules: [
    { t: "Every reconciliation/query engine scopes to {branch,'ALL'} (bank, client, supplier, tally, collections, ageing) so no branch's data leaks into another.", r: 'clientReco.service.js:50 · supplierReco.service.js:36 · tallyReco.service.js:20' },
    { t: "Consolidated (branch='ALL') ageing returns a per-branch breakdown in each branch's OWN currency — never a merged cross-branch/cross-currency total.", r: 'accounting.service.js:2505' },
    { t: 'Auto-created/migrated ledgers are branch-owned: everything except shared income/sales/purchase/expense heads is scoped to the posting branch.', r: 'ledgerScope.js:40' },
    { t: 'Taxes/Suppliers/Customers/Loans/Banks/Capital are branch-specific (keeps India-GST out of Africa-VAT branches).', r: 'ledgerScope.js:18' },
    { t: 'TK Group in-scope check: an actor with allBranches or no branch list passes; otherwise the branch must be in the actor\'s branches.', r: 'tk-group/integration.js:58' },
    { t: 'A branch-scoped user is confined to their own branch(es); out-of-scope ?branch or body.branch → 403; consolidated view is coerced to their branch.', r: 'auth.middleware.js:102' },
    { t: 'A scoped user with an empty branch list gets NO implicit org-wide access (fail-closed).', r: 'auth.middleware.js:94' },
    { t: 'An explicit branch restriction confines even an otherwise all-scope role.', r: 'auth.middleware.js:84' },
    { t: "A branch-scoped user cannot read/edit/delete another branch's record by guessing its id — the CRUD factory enforces branch ownership (404).", r: 'crudFactory.js:89' },
    { t: 'The "post-migration = live" behaviour is structural (posted vouchers are simply live book data), NOT a hardcoded date gate — the only hardcoded cutover in code is the TCS 206C 2026-04-01 rate switch.', r: 'voucherSpecs.js:90', regime: 'all' },
  ]},
  { id: 'W', group: 'ops', title: 'Roles, Permissions, Access & Login', blurb: 'Authentication, the ERP access kill-switch, view-only writes, and role-gated control-plane masters.', rules: [
    { t: 'Every request requires a valid Bearer token (except open-mode, which is hard-refused in production).', r: 'auth.middleware.js:164,174' },
    { t: 'A view-only user may read but every write (POST/PUT/PATCH/DELETE) is rejected — globally, with a "View only" toast.', r: 'auth.middleware.js:139' },
    { t: "A JWT issued before the user's last password change is rejected (logout-everywhere).", r: 'auth.middleware.js:190' },
    { t: "A session is evicted mid-flight when the user's Books (ERP) access toggle is switched off.", r: 'auth.middleware.js:195' },
    { t: 'requireRole gates return 403 "Insufficient permissions" when the actor\'s role isn\'t in the allow-list.', r: 'auth.middleware.js:204' },
    { t: 'Login is rejected for an inactive user or bad credentials.', r: 'auth.service.js:64' },
    { t: 'Books login is hard-blocked when access.erp === false (admin kill-switch).', r: 'auth.service.js:78' },
    { t: 'Books login requires an active BooksAccess grant; ERP role + branch scope come only from the separate BooksAccess collection, never the shared CRM user doc.', r: 'auth.service.js:87,88' },
    { t: 'ERP access is update-only — grant/revoke is an update; stray create/delete fail loudly (400).', r: 'userAccess.service.js:73' },
    { t: 'ERP is deny-by-default (only an active grant enables Books); CRM allow-by-default for active users; App deny-by-default.', r: 'userAccess.controller.js:33' },
    { t: 'Flipping who can log into which app (CRM/ERP toggles) is admin-only (Super Admin/Director/Senior Finance Manager).', r: 'userAccess.route.js:13' },
    { t: "Editing roles/permissions is admin-only; built-in (system) roles cannot be deleted and the system flag can't be flipped via API.", r: 'roles.route.js:9 · roles.controller.js:43,55' },
    { t: 'Approval-rules, approval-limits and field-access masters are admin-write only; reads open to any authenticated user.', r: 'approvalRules.route.js:5 · approvalLimits.route.js:5' },
  ]},
  { id: 'Y', group: 'ops', title: 'Frontend Enforcement & UX Guards', blurb: "The UI layer that mirrors the server — pre-disabling buttons and blocking submits so a stale screen can't post past the backend.", rules: [
    { t: 'Future date is blocked on every voucher form via a date max=today wrapper (Receipt/Payment, Journal, Contra, Purchase-Expense, Debit Note, Refund/Reissue, Refund-Partial, ADM/ACM, legacy).', r: 'SmartDateInput.jsx:8 + all *Fields.jsx' },
    { t: 'Only full-scope roles (Super Admin, Director, Senior Finance Manager, Sr. Accounts Executive) see every branch and the "ALL" view; a non-full-scope user with no assigned branch resolves to NULL (no all-branch fallback).', r: 'branchScope.js:10,52' },
    { t: 'The branch switcher lists only the user\'s assigned branches; the "ALL" consolidated row is offered only to full-scope users with more than one branch.', r: 'BranchSwitcher.jsx:39,40' },
    { t: 'The inter-branch destination list excludes the origin branch; an INB voucher is valid only with from-branch, to-branch, date and positive total.', r: 'soPoGpVoucherEntry.jsx:453,648' },
    { t: 'Save is disabled unless the form validates, a SPECIFIC branch is set (never "All"), it\'s not saving, and the account is not view-only.', r: 'VoucherShell.jsx:63,210' },
    { t: 'Approved/saved/posted vouchers are read-only in the drill-down; a parent-locked voucher can never be edited or revoked alone — act on the parent.', r: 'VoucherShell.jsx:228 · useRevokeAction.js:16' },
    { t: 'The live journal must balance — the shell shows "✓ Balanced" vs "✗ Out by <amt>" and flags missing/uncreated ledgers; a ledger not in the chart cannot be approved.', r: 'VoucherShell.jsx:146 · legacy.jsx:1106' },
    { t: 'Revoke is gated to approver roles, runs a server preflight that hard-blocks (locked/bank-reconciled/live-refund), and requires a typed reason.', r: 'useRevokeAction.js:51,58,64' },
    { t: 'In the approvals queue, Delete shows only to admins, Revoke only to approvers, Approve is disabled unless the voucher is postable AND the user is allowed at its stage; reject/delete require a reason.', r: 'voucherApprovals.jsx:75,197,333' },
    { t: 'The Pending tab shows every pending voucher with NO date filter (all must be visible for approval); INB refunds are excluded from the SO/PO/GP queue.', r: 'voucherApprovals.jsx:106,108' },
    { t: 'Pipeline order is Branch → AE·Sughra → Director·Farhan → Owner·Afshin → FM·Faiz, FM last; Director/Owner beads appear only when the escalation flag is engaged AND the amount crosses the ceiling.', r: 'approvalPipeline.js:102,131' },
    { t: 'Amounts are formatted in the branch currency (₹ India lakh/crore vs $ Western thousands) and ₹ + $ are NEVER summed together — only counts are currency-neutral.', r: 'format.js:47 · approvalPipeline.js:50', regime: 'all' },
    { t: 'Export guard: a branch-scoped user cannot export a consolidated/group report and view-only users cannot export under the restrict policy; every export attempt is logged.', r: 'exportGuard.js:49,53,99' },
    { t: 'Locked ledgers render a 🔒 badge and wired ledgers carry the ~* marker; both cannot be created/edited/deleted/deactivated from the app, and the ledger Code field is auto-generated read-only.', r: 'LedgerLabel.jsx:37 · mastersLive.jsx:260,603,609' },
    { t: 'Chart-of-Accounts fixed structure (Parent Group/Group/Sub-Group) and module/tax-wired nodes are locked — cannot be created, edited or deleted.', r: 'chartBuilder.jsx:50,255' },
    { t: 'Per-voucher-type registry validators enforce required fields + balance: Journal Dr=Cr with ≥2 lines; Contra distinct accounts; Receipt/Payment party+bank+positive+valid allocation; Refund reference+customer+supplier+positive; etc.', r: 'registry.jsx:163,384,428' },
    { t: 'Bill allocation is clamped: positive rows to [0, outstanding], overpaid rows to [−overpaid, 0] — cannot over-allocate; TDS applies only on genuine supplier payments / customer receipts, never a client refund.', r: 'ReceiptPaymentFields.jsx:63 · registry.jsx:128', regime: 'all' },
    { t: 'Verifying a payment generates the tax invoice and cannot be undone (explicit confirm); rejecting needs a reason; clarification needs a note.', r: 'paymentVerification.jsx:50,57,61' },
    { t: 'GP% is banded by threshold for colour (≥20 green, ≥12 teal, ≥8 amber, else red; KPI accent ≥15/≥10).', r: 'gp-report.jsx:33,191' },
    { t: 'Draft autosave: every non-sensitive field is debounced to localStorage keyed by route→field, restored only into EMPTY fields, cleared on any 2xx save; sensitive types and data-no-persist subtrees are never stored.', r: 'formPersistence.js:27,122,144,198' },
    { t: 'The month-close checklist bank-reco / debtors-review / cash-count items are manual ticks the accountant must set (not auto-derived).', r: 'accountantWorkspace.jsx:1158' },
  ]},
];

// Derived helpers — never hand-maintain counts.
export function ruleBookStats(book = RULE_BOOK) {
  const total = book.reduce((n, d) => n + d.rules.length, 0);
  const accounts = book.filter((d) => d.group === 'accounts').reduce((n, d) => n + d.rules.length, 0);
  return { total, accounts, ops: total - accounts, domains: book.length };
}

export const RULE_GROUP_LABEL = { accounts: 'Accounts', ops: 'Operations' };

// Regroup the flat GET /api/rules registry into the RULE_BOOK shape (one section per
// domain). Shared by the Rule Book tab AND the Control Panel's ERP-Law band so both read
// the domains identically. regime is preserved only when explicit ('' → undefined so
// ruleRegime() derives it from the text, as with the bundled data). Returns null when
// there is nothing to show, so the caller falls back to the bundled RULE_BOOK.
export function regroupRegistry(items) {
  if (!items || !items.length) return null;
  const map = new Map();
  const order = [];
  for (const it of items) {
    // Key on domainCode (the canonical mnemonic), NOT domain: flatten rows carry the letter
    // (A, Q, N…) while curated rows carry the mnemonic (GST, APPR, RECON…) — same domain, so
    // keying on `domain` split each into two identically-titled sections. domainCode unifies them.
    const key = it.domainCode || it.domain;
    if (!map.has(key)) {
      map.set(key, { id: key, group: it.group, title: it.domainTitle, blurb: it.domainBlurb || '', rules: [] });
      order.push(key);
    }
    map.get(key).rules.push({ t: it.title, r: it.sourceRef, regime: it.regime || undefined });
  }
  return order.map((id) => map.get(id));
}

// The ERP-Law band (Control Panel plane ①) shows only the LOCKED law floor — the immutable
// laws. Owner-controlled rules (approval authority, statutory rates) are OPERATED in the
// Owner & Authority plane, so they are not shown here as unchangeable law. Falls back to
// regrouping ALL items when none carry a govern tag (older backend), then to the bundled
// book — so the band is never blank.
export function lockedLawBook(items, fallback = RULE_BOOK) {
  if (items && items.length) {
    const locked = items.filter((it) => it.govern === 'locked');
    return regroupRegistry(locked.length ? locked : items) || fallback;
  }
  return fallback;
}
